language: python
script: nosetests
matrix:
  include:
    - python: "2.7"
      install:
        - ./install-cloudinit.sh 0.6.3
        - pip install pyyaml Cheetah
    - python: "2.7"
      install:
        - ./install-cloudinit.sh 0.7.5
        - pip install pyyaml Cheetah requests
    - python: "3.4"
      install:
        - ./install-cloudinit.sh 0.7.7
        - pip install -r vendor/cloud-init/requirements.txt
    - python: "3.4"
      install:
        - ./install-cloudinit.sh 0.7.8
        - pip install -r vendor/cloud-init/requirements.txt
