language: python
script: nosetests
matrix:
  include:
    - python: "2.7"
      install:
        - ./install-cloudinit.sh 0.6.3
        - pip install pyyaml Cheetah
    - python: "2.7"
      install:
        - ./install-cloudinit.sh 0.7.5
        - pip install pyyaml Cheetah
    - python: "3.4"
      install:
        - ./install-cloudinit.sh 1160
        - pip install -r vendor/cloud-init/requirements.txt
addons:
  apt:
    packages:
      - bzr
